var music=addTree("music","tree");
var string=addTree("string","tree");
var wind=addTree("wind","tree");
var percussion=addTree("percussion","tree");
var cello=addTree("cello","node");
var violin=addTree("violin","node");
var bass=addTree("bass","node");
var strings=addNode("strings");
var fingering=addNode("fingering");
var reading=addNode("reading");
var notes=addNode("notes");
addNodeToTree(music,string);
addNodeToTree(music,wind);
addNodeToTree(music,percussion);
addNodeToTree(music,cello);
addNodeToTree(music,violin);
addNodeToTree(music,bass);
addNodeToTree(cello,strings);
addNodeToTree(cello,fingering);
addNodeToTree(cello,reading);
addNodeToTree(cello,notes);
addConnection(music,string,cello);
addConnection(music,string,violin);
addConnection(music,string,bass);
addConnection(cello,strings,notes);
addConnection(cello,fingering,notes);
addUserCategory("100001711440164",music);
